name: Static Analysis

on:
    pull_request: null
    push:
        branches:
            - develop
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['8.0']

        name: Unit Tests [${{ matrix.php }}]
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none
                    tools: composer:v2
            -   run: git --version
            -   run: git config --global user.email "test@github.com"
            -   run: git config --global user.name "GitHub Action"
            -   run: git --version
            -   run: composer clearcache
            -   run: composer install --no-progress --ansi
            -   run: composer phpstan
